python3 Code/to_rosette.py Code/Examples/archimedes/archimedes.c benchmarks-rosette/archimedes.rkt
python3 Code/to_rosette.py Code/Examples/berkeley/berkeley.c benchmarks-rosette/berkeley.rkt
python3 Code/to_rosette.py Code/Examples/closest_cube_root/closest_cube_root.c benchmarks-rosette/closest_cube_root.rkt
python3 Code/to_rosette.py Code/Examples/closest_square_root/closest_square_root.c benchmarks-rosette/closest_square_root.rkt
python3 Code/to_rosette.py Code/Examples/cohendiv/cohendiv.c benchmarks-rosette/cohendiv.rkt
python3 Code/to_rosette.py Code/Examples/consecutive_cubes/consecutive_cubes.c benchmarks-rosette/consecutive_cubes.rkt
python3 Code/to_rosette.py Code/Examples/dijkstra_ind/dijkstra_ind.c benchmarks-rosette/dijkstra_ind.rkt
python3 Code/to_rosette.py Code/Examples/dijsktra/dijsktra.c benchmarks-rosette/dijsktra.rkt
python3 Code/to_rosette.py Code/Examples/divbin/divbin.c benchmarks-rosette/divbin.rkt
python3 Code/to_rosette.py Code/Examples/euclidex1/euclidex1.c benchmarks-rosette/euclidex1.rkt
python3 Code/to_rosette.py Code/Examples/euclidex2/euclidex2.c benchmarks-rosette/euclidex2.rkt
python3 Code/to_rosette.py Code/Examples/fermat1/fermat1.c benchmarks-rosette/fermat1.rkt
python3 Code/to_rosette.py Code/Examples/fermat2_ind/fermat2_ind.c benchmarks-rosette/fermat2_ind.rkt
python3 Code/to_rosette.py Code/Examples/firefly/firefly.c benchmarks-rosette/firefly.rkt
python3 Code/to_rosette.py Code/Examples/floor_square_root/floor_square_root.c benchmarks-rosette/floor_square_root.rkt
python3 Code/to_rosette.py Code/Examples/friction/friction.c benchmarks-rosette/friction.rkt
python3 Code/to_rosette.py Code/Examples/illinois/illinois.c benchmarks-rosette/illinois.rkt
python3 Code/to_rosette.py Code/Examples/lcm1/lcm1.c benchmarks-rosette/lcm1.rkt
python3 Code/to_rosette.py Code/Examples/mannadiv_Carre/mannadiv_Carre.c benchmarks-rosette/mannadiv_Carre.rkt
python3 Code/to_rosette.py Code/Examples/mannadiv_Cube/mannadiv_Cube.c benchmarks-rosette/mannadiv_Cube.rkt
python3 Code/to_rosette.py Code/Examples/mannadiv_ind/mannadiv_ind.c benchmarks-rosette/mannadiv_ind.rkt
python3 Code/to_rosette.py Code/Examples/mesi/mesi.c benchmarks-rosette/mesi.rkt
python3 Code/to_rosette.py Code/Examples/moesi/moesi.c benchmarks-rosette/moesi.rkt
python3 Code/to_rosette.py Code/Examples/petter10/petter10.c benchmarks-rosette/petter10.rkt
python3 Code/to_rosette.py Code/Examples/petter3/petter3.c benchmarks-rosette/petter3.rkt
python3 Code/to_rosette.py Code/Examples/petter5/petter5.c benchmarks-rosette/petter5.rkt
python3 Code/to_rosette.py Code/Examples/polynomial_approx/polynomial_approx.c benchmarks-rosette/polynomial_approx.rkt
python3 Code/to_rosette.py Code/Examples/positive_square_with_holes/positive_square_with_holes.c benchmarks-rosette/positive_square_with_holes.rkt
python3 Code/to_rosette.py Code/Examples/positive_square_with_number_holes/positive_square_with_number_holes.c benchmarks-rosette/positive_square_with_number_holes.rkt
python3 Code/to_rosette.py Code/Examples/readerswriters/readerswriters.c benchmarks-rosette/readerswriters.rkt
python3 Code/to_rosette.py Code/Examples/square_roots/square_roots.c benchmarks-rosette/square_roots.rkt
python3 Code/to_rosette.py Code/Examples/sum_of_two_vars/sum_of_two_vars.c benchmarks-rosette/sum_of_two_vars.rkt
python3 Code/to_rosette.py Code/Examples/wensley_division/wensley_division.c benchmarks-rosette/wensley_division.rkt
